Repository jan-oxymoron/project-hospital-translations, pull requests merged in 2018-11, with the labels that each got.

#711 Update StringTableNlSymptoms.xml
  localization-pack-nl/StringTableNlSymptoms.xml
Labels: question

#687 Update StringTableKrSymptoms.xml
  localization-pack-kr/StringTableKrSymptoms.xml
Labels: invalid

#761 Create StringTableCaOptions.xml
  localization-pack-ca/StringTableCaOptions.xml
Labels: question

#763 Update StringTableTrBuildingMode.xml
  localization-pack-tr/StringTableTrBuildingMode.xml
Labels: NOT READY!
