Repository jan-oxymoron/project-hospital-translations, pull requests merged in 2018-10, with the labels that each got.

#14 Update StringTableEsCharacters.xml
  localization-pack-es/StringTableEsCharacters.xml
Labels: question

#35 WIP: EN: Revision of BuildingMode
  localization-proofreading-english/StringTableEnBuildingMode.xml
Labels: NOT READY!

#132 WIP: Revision of skills
  localization-proofreading-english/StringTableEnSkills.xml
Labels: NOT READY!

#113 WIP: Revision of English Diagnoses
  localization-proofreading-english/StringTableEnDiagnoses.xml
Labels: NOT READY!

#234 Update StringTableDeTutorial.xml line 210 - 218
  localization-pack-de/StringTableDeTutorial.xml
Labels: NOT READY!

#203 Update StringTableEsTreatments.xml
  localization-pack-es/StringTableEsTreatments.xml
Labels: invalid

#318 Update StringTableKrUI.xml
  localization-pack-kr/StringTableKrUI.xml
Labels: NOT READY!

#265 Update StringTableJaUI.xml
  localization-pack-ja/StringTableJaUI.xml
Labels: question

#210 WIP: Revision of symptoms
  localization-proofreading-english/StringTableEnSymptoms.xml
Labels: NOT READY!

#298 Update StringTableEnExaminations.xml
  localization-proofreading-english/StringTableEnExaminations.xml
Labels: help wanted

#444 WIP: More symptoms
  localization-proofreading-english/StringTableEnSymptoms.xml
Labels: NOT READY!

#448 WIP: Diagnoses
  localization-proofreading-english/StringTableEnDiagnoses.xml
Labels: NOT READY!
